name: Assign issue to contributor
on:
  pull_request:
  issue_comment:
    types:  [created, edited]
    
jobs:
  assign:
    if: ${{ github.event.comment.body }} == *.take1*
    runs-on: ubuntu-latest
    steps:
    - name: take the issue
      uses: bdougie/take-action@main
      env:
        GITHUB_TOKEN: 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
      with:
        message: Thanks for taking this issue! Let us know if you have any questions!
        trigger: .take